### Register Student
POST localhost:8080/authentication/register
Content-Type: application/json

{
  "username": "student",
  "password": "123",
  "firstName": "dang",
  "lastName": "nguyen",
  "personRole": "STUDENT"
}

### Register Faculty
POST localhost:8080/authentication/register
Content-Type: application/json

{
  "username": "faculty",
  "password": "123",
  "firstName": "Paymen",
  "lastName": "Salek",
  "personRole": "FACULTY"
}

### GET Barcode Record
GET localhost:8080/barcoderecord
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdHVkZW50Iiwicm9sZSI6WyJTdHVkZW50Il0sImV4cCI6MTYyMjc3MDQzNywiaWF0IjoxNjIyNzUyNDM3fQ.yPzvy_1THjS-NWKqf77oC-DvL2NjNLeRTbyAONkXhkY

# FACULTY eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmYWN1bHR5Iiwicm9sZSI6WyJGYWN1bHR5Il0sImV4cCI6MTYyMjc2ODUwOCwiaWF0IjoxNjIyNzUwNTA4fQ.JIov2Jo4aBAArJtkNAHO8iFAhKSSri-xVfpCGf7ySlw
# STUDENT eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdHVkZW50Iiwicm9sZSI6WyJTdHVkZW50Il0sImV4cCI6MTYyMjc2ODAwNSwiaWF0IjoxNjIyNzUwMDA1fQ.AW93cOvtNd66Q5xPHYFSqov8RNK0kHfJD0OiQpz9A8w