### Login
POST localhost:8080/authentication/login
Content-Type: application/json

{
  "username": "stellavera",
  "password": "123"
}

### Register Student
POST localhost:8080/authentication/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5nIiwicm9sZSI6WyJTVFVERU5UIiwiUEVSU09OTkVMIiwiQURNSU4iXSwiZXhwIjoxNjIzMTE4NjU1LCJpYXQiOjE2MjMxMDA2NTV9.n4AN3th3Nxt3zEhDCgDHwtGs1DjFViJDOOy9GXjDa4I

{
  "username": "admin6",
  "password": "1234",
  "firstName": "ADMIN",
  "lastName": "MR",
  "personRole": "ADMIN"
}

### Register Student
POST localhost:8080/authentication/register
Content-Type: application/json

{
  "username": "student",
  "password": "123",
  "firstName": "dang",
  "lastName": "nguyen",
  "personRole": "STUDENT"
}

### Register Faculty
POST localhost:8080/authentication/register
Content-Type: application/json

{
  "username": "faculty",
  "password": "123",
  "firstName": "Payman",
  "lastName": "Salek",
  "personRole": "FACULTY"
}

### POST Create barcode record
POST localhost:8080/barcoderecord
Content-Type: application/json

{
  "locationId": "1",
  "barcode": "9423c2e8-7ca4-4c82-8047-d8a87640aaff"
}

### GET Barcode Record
GET localhost:8080/barcoderecord
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5nIiwicm9sZSI6WyJTVFVERU5UIl0sImV4cCI6MTYyMzExNzAyOCwiaWF0IjoxNjIzMDk5MDI4fQ.2NLzlfjmTeVyQ6UZKYCIoX6t3JIYbVI9nM6PwQ2WcEg

### GET All persons
GET localhost:8080/admin/persons/

### Admin assigne Role
### Register Faculty
PATCH localhost:8080/admin/persons/2/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjQiLCJyb2xlIjpbIkFETUlOIl0sImV4cCI6MTYyMzExNzI0NSwiaWF0IjoxNjIzMDk5MjQ1fQ.dcP4300eSjRyYIgfyD3eHcKy5dfouN6m3Z0jVomdeHc

{
  "roles": [
    {
      "role": "student",
      "properties": {
        "studentId": "612345"
      },
      "active": false
    },
    {
      "role": "personnel",
      "properties": null,
      "active": true
    },
    {
      "role": "admin",
      "properties": null,
      "active": true
    }
  ]
}

### Get all coures teach by a faculty
GET localhost:8080/faculty/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdGVsbGF2ZXJhIiwicm9sZSI6WyJGQUNVTFRZIl0sImV4cCI6MTYyMzIyMjgzMywiaWF0IjoxNjIzMjA0ODMzfQ.Zoi6Wtix2W_Oof5AQlH0m9IUnUQJgKDDRyWv-7Mbi44

### attendance
POST localhost:8080/personnel/attendancev2
Content-Type: application/json

{
  "courseOfferId":1,
  "studentId": 2
}