### Login
POST localhost:8080/authentication/login
Content-Type: application/json

{
  "username": "admin3",
  "password": "123"
}

### Register Student
POST localhost:8080/authentication/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOlsiQURNSU4iXSwiZXhwIjoxNjIzMTA0NTc4LCJpYXQiOjE2MjMwODY1Nzh9.pcbkJ0_WHwkxgM2O-DyF1Y3wE2fGHTG1PDmbEJ58S2Y

{
  "username": "admin3",
  "password": "123",
  "firstName": "ADMIN",
  "lastName": "MR",
  "personRole": "ADMIN"
}

### Register Student
POST localhost:8080/authentication/register
Content-Type: application/json

{
  "username": "student",
  "password": "123",
  "firstName": "dang",
  "lastName": "nguyen",
  "personRole": "STUDENT"
}

### Register Faculty
POST localhost:8080/authentication/register
Content-Type: application/json

{
  "username": "faculty",
  "password": "123",
  "firstName": "Payman",
  "lastName": "Salek",
  "personRole": "FACULTY"
}

### POST Create barcode record
POST localhost:8080/barcoderecord
Content-Type: application/json

{
  "classSessionId": "id001",
  "locationId": "locationId001"
  "attendanceDate": "timestamp001"
}

### GET Barcode Record
GET localhost:8080/barcoderecord
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdHVkZW50Iiwicm9sZSI6WyJTdHVkZW50Il0sImV4cCI6MTYyMjc3MDQzNywiaWF0IjoxNjIyNzUyNDM3fQ.yPzvy_1THjS-NWKqf77oC-DvL2NjNLeRTbyAONkXhkY


### Admin assigne Role
### Register Faculty
PATCH localhost:8080/admin/persons/2/roles
Content-Type: application/json

{
  "roles": [
    {
      "role": "student",
      "properties": {
        "studentId": "612345"
      },
      "active": true
    },
    {
      "role": "personnel",
      "properties": null,
      "active": true
    }
  ]
}
